"""empty message

Revision ID: 58cbe320ba48
Revises: 
Create Date: 2017-08-24 01:07:36.889173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58cbe320ba48'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('music',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('music_id', sa.Integer(), nullable=True),
    sa.Column('music_name', sa.String(), nullable=True),
    sa.Column('music_cover_image', sa.String(), nullable=True),
    sa.Column('music_artist_name', sa.String(), nullable=True),
    sa.Column('music_difficulty', sa.Integer(), nullable=True),
    sa.Column('music_level', sa.String(), nullable=True),
    sa.Column('music_base_rate', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(), nullable=True),
    sa.Column('user_friend_code', sa.String(), nullable=True),
    sa.Column('user_hash', sa.String(), nullable=True),
    sa.Column('user_play_count', sa.Integer(), nullable=True),
    sa.Column('rate_display', sa.Integer(), nullable=True),
    sa.Column('rate_highest', sa.Integer(), nullable=True),
    sa.Column('rate_best', sa.Integer(), nullable=True),
    sa.Column('rate_recent', sa.Integer(), nullable=True),
    sa.Column('rate_max', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('music')
    op.drop_table('admin')
    # ### end Alembic commands ###
